defmodule BounceApiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :bounce_api

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_bounce_api_key",
    signing_salt: "OyRlYCnz",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :bounce_api,
    gzip: not code_reloading?,
    only: BounceApiWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :bounce_api
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Allow the Vite dev server (and configured origins) to call the JSON API.
  plug CORSPlug, origin: &BounceApiWeb.Endpoint.cors_origins/0

  plug BounceApiWeb.Router

  @doc """
  CORS origins allowed to call the API. Configured via `:cors_origins`
  (see `config/*.exs`); defaults to the Vite dev server.
  """
  def cors_origins do
    Application.get_env(:bounce_api, :cors_origins, ["http://localhost:5173"])
  end
end
